name: print_helper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  badges: ^3.1.2
  shimmer: ^3.0.0
  provider: ^6.0.4
  share_plus: ^12.0.0
  photo_view: ^0.15.0
  flutter_svg: ^2.0.2
  jwt_decoder: ^2.0.1
  torn_ticket: ^0.1.0
  image_picker: ^1.2.0
  fluttertoast: ^9.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2
  skeletonizer: ^2.1.0+1
  delayed_display: ^2.0.0
  webview_flutter: ^4.13.0
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^10.0.0
  internet_connection_checker: ^3.0.1
  carousel_slider: ^5.1.1
  file_picker: ^10.3.6
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.3
  dart_pusher_channels: ^1.2.3
  emoji_picker_flutter: ^4.4.0
  flutter_local_notifications: ^19.5.0
  record: ^6.1.2
  just_audio: ^0.10.5
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  audio_waveforms: ^2.0.2
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

